groups:
- Motion Cam Outdoor
- Motion Cam
- Motion Protect
- Street Siren
- Dual Curtaine Outdoor
devices:
- key: MCO_BACK_M3x10
  name: MCO
  holes: 4
  what: BACK
  screw_size: M3x10
  task: '0'
  torque: 0.49
  work_x: 110.0
  work_y: 500.0
  work_feed: 50000.0
  group: Motion Cam Outdoor
  fixture: 3SD-ST-E_MCO-P_BK-S_310
  coord_source: ''
  program:
  - type: WORK
    x: 54.0
    y: 28.9
    f: 50000.0
  - type: FREE
    x: 84.0
    y: 28.9
    f: 50000.0
  - type: FREE
    x: 84.0
    y: -27.6
    f: 50000.0
  - type: WORK
    x: 54.2
    y: -27.6
    f: 50000.0
  - type: FREE
    x: 54.2
    y: -37.6
    f: 50000.0
  - type: FREE
    x: -55.8
    y: -37.6
    f: 50000.0
  - type: WORK
    x: -55.8
    y: -29.1
    f: 50000.0
  - type: FREE
    x: -85.8
    y: -29.1
    f: 50000.0
  - type: FREE
    x: -85.8
    y: 30.9
    f: 50000.0
  - type: WORK
    x: -55.8
    y: 29.9
    f: 50000.0
- key: MP_BACK_M3x16
  name: MP
  holes: 3
  what: BACK
  screw_size: M3x16
  task: '1'
  torque: 0.6
  work_x: 110.0
  work_y: 500.0
  work_feed: 50000.0
  group: Motion Protect
  fixture: 3SD-ST-E_MP-P_BK-S_316
  coord_source: ''
  program:
  - type: WORK
    x: -17.1
    y: 2.0
    f: 50000.0
  - type: WORK
    x: 12.9
    y: -18.5
    f: 50000.0
  - type: WORK
    x: 12.9
    y: 21.5
    f: 50000.0
- key: MCO_PHOD_BACK_M3x10
  name: MCO_PHOD
  holes: 4
  what: BACK
  screw_size: M3x10
  task: '0'
  torque: 0.49
  work_x: 110.0
  work_y: 500.0
  work_feed: 50000.0
  group: Motion Cam Outdoor
  fixture: 3SD-ST-E_MCO-P_BK-S_310
  coord_source: MCO_BACK_M3x10
  program: []
- key: MCO_HM_BACK_M3x10
  name: MCO_HM
  holes: 4
  what: BACK
  screw_size: M3x10
  task: '0'
  torque: 0.49
  work_x: 110.0
  work_y: 500.0
  work_feed: 50000.0
  group: Motion Cam Outdoor
  fixture: 3SD-ST-E_MCO-HM-P_BK-S_310
  coord_source: ''
  program:
  - type: WORK
    x: 61.9
    y: 33.0
    f: 50000.0
  - type: FREE
    x: 101.9
    y: 33.0
    f: 50000.0
  - type: FREE
    x: 101.9
    y: -30.5
    f: 50000.0
  - type: WORK
    x: 61.9
    y: -30.5
    f: 50000.0
  - type: FREE
    x: 61.9
    y: -40.5
    f: 50000.0
  - type: FREE
    x: -68.6
    y: -40.5
    f: 50000.0
  - type: WORK
    x: -68.6
    y: -30.5
    f: 50000.0
  - type: FREE
    x: -98.6
    y: -30.5
    f: 50000.0
  - type: FREE
    x: -98.6
    y: 33.0
    f: 50000.0
  - type: WORK
    x: -68.6
    y: 33.0
    f: 50000.0
- key: MPO_BACK_M3x10
  name: MPO
  holes: 2
  what: BACK
  screw_size: M3x10
  task: '0'
  torque: 0.49
  work_x: 110.0
  work_y: 500.0
  work_feed: 50000.0
  group: Motion Protect
  fixture: 3SD-ST-E_MPO-P_BK-S_310
  coord_source: ''
  program:
  - type: FREE
    x: 84.4
    y: -45.0
    f: 50000.0
  - type: FREE
    x: -10.6
    y: -35.0
    f: 50000.0
  - type: WORK
    x: -2.6
    y: -26.0
    f: 50000.0
  - type: FREE
    x: -2.6
    y: -36.0
    f: 50000.0
  - type: FREE
    x: 77.4
    y: -36.0
    f: 50000.0
  - type: FREE
    x: 77.4
    y: 44.0
    f: 50000.0
  - type: FREE
    x: -15.6
    y: 44.0
    f: 50000.0
  - type: WORK
    x: -2.6
    y: 29.0
    f: 50000.0
  - type: FREE
    x: -2.6
    y: 39.0
    f: 50000.0
- key: MPPS_BACK_M3x16
  name: MPPS
  holes: 3
  what: BACK
  screw_size: M3x16
  task: '1'
  torque: 0.6
  work_x: 110.0
  work_y: 500.0
  work_feed: 50000.0
  group: Motion Protect
  fixture: 3SD-ST-E_MP-P_BK-S_316
  coord_source: MP_BACK_M3x16
  program: []
- key: CP_BACK_M3x16
  name: CP
  holes: 3
  what: BACK
  screw_size: M3x16
  task: '1'
  torque: 0.6
  work_x: 110.0
  work_y: 500.0
  work_feed: 50000.0
  group: Motion Protect
  fixture: 3SD-ST-E_MP-P_BK-S_316
  coord_source: MP_BACK_M3x16
  program: []
- key: CPS_BACK_M3x16
  name: CPS
  holes: 3
  what: BACK
  screw_size: M3x16
  task: '1'
  torque: 0.6
  work_x: 110.0
  work_y: 500.0
  work_feed: 50000.0
  group: Motion Protect
  fixture: 3SD-ST-E_MP-P_BK-S_316
  coord_source: MP_BACK_M3x16
  program: []
- key: MPF_BACK_M3x16
  name: MPF
  holes: 1
  what: BACK
  screw_size: M3x16
  task: '1'
  torque: 0.6
  work_x: 110.0
  work_y: 500.0
  work_feed: 50000.0
  group: Motion Protect
  fixture: 3SD-ST-E_MP-P_BK-S_316
  coord_source: ''
  program:
  - type: WORK
    x: 16.0
    y: 0.0
    f: 50000.0
- key: CPF_BACK_M3x16
  name: CPF
  holes: 1
  what: BACK
  screw_size: M3x16
  task: '1'
  torque: 0.6
  work_x: 110.0
  work_y: 500.0
  work_feed: 5000.0
  group: Motion Protect
  fixture: 3SD-ST-E_MP-P_BK-S_316
  coord_source: MP_BACK_M3x16
  program: []
